import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Landing from './Landing'
import Services from './Services'
import Projects from './Projects'
import About from './About'
import Contact from './Contact'
import Footer from '../components/Footer'
import Nav from '../components/Nav'
import { useRouter } from 'next/router'
import { MdOutlineRequestQuote } from 'react-icons/md'
import { BiPhoneCall } from 'react-icons/bi'




export default function Index() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>AD Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav/>
        <Landing/>
        <Footer/>
      </main>
    </>
  )
}

  
